spring:
  mvc:
    static-path-pattern: /static/**
  datasource:
    druid:
      url:  jdbc:mysql://localhost:3306/exam?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
#      username: root
      username: exam
      password: iZtEJBwm8KpERXAY
#      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver
#主键自增
mybatis-plus:
  global-config:
    db-config:
      id-type: auto


manager:
  config:
    interval: 30
    pagesize: 30
    timegap: 15
    minfilesize: 512
    maxfilesize: 131072
    candelete: true
    interval_desc: 指定扫描考试信息的间隔时间，单位为 分钟。
    pagesize_desc: 指定分页查询时每页显示记录数的默认值（查询页面中可以更改）。
    timegap_desc: 指定手工开启考试时允许的最大提前量，单位为分钟
    minfilesize_desc: 指定上传文件的长度下限（字节），低于此值发出警告
    maxfilesize_desc: 指定上传文件的长度上限（字节），高于此值发出警告
    candelete_desc: 设置是否允许教师自己清理和删除考试信息。
server:
  port: 8081
